### ISSUE TITLE
Solution not working for VB.Net project

### ISSUE THREAD

**Issue by komapatel** [aspnet/AspNetWebFormsDependencyInjection#11]
I am trying to implement DI using this package in my web project but it is not working for me. when i follow steps mentioned at https://devblogs.microsoft.com/aspnet/use-dependency-injection-in-webforms-application/?WT.mc_id=ondotnet-channel9-cephilli
1.	I tried upgrading my existing VB.Net Web application --- The web page constructor with parameter never fired
2.	Tried with creating a new Vb.Net web application targeting .Net 4.7.2 -- The web page constructor never fired
3.	Tried with creating a new c# web application targeting .Net 4.7.2 -- Stack trace with 'Constructor of type not found.'
Please help me with understanding if this package is working for vb.net web form applications.

**Comment by Kesmy** [comment]
@komapatel Recently had to deal with this.

Verify that all of your constructor parameters have registrations, and that they aren't throwing their own exceptions during resolution. You'll have to wade through a sea of Unity resolution exceptions, but you might also be able to find the exception causing your exception in the VS debug output

This implementation swallows all of the exceptions it gets, then ends up calling `Activator.CreateInstance`, which fails with that `Constructor on type not found`.

Once I figured out what my offending type was and fixed the registration, I was able to get DI working in a `Page`

**Comment by StephenMolloy** [comment]
Thanks for the help @Kesmy. I hope it got the OP unstuck. However, I'm closing this issue without addressing the swallows-all-exceptions behavior in the sample code because this is not an actively supported project.

> **Warning**
> _This project demonstrates building a dependency injection adapter for the [Unity](https://github.com/unitycontainer/unity) IoC container. **It is a point of reference** for other adapter authors. Please note that this implementation is for demonstration purposes only and **is not being actively maintained.**_
