### ISSUE TITLE
Using IoC container other than Unity

### ISSUE THREAD

**Issue by ndc** [aspnet/AspNetWebFormsDependencyInjection#3]
Hi,

Is it possible to use non Unity IoC container?

If I want to modify this project to use different IoC container, which part should I modify?

**Comment by ndc** [comment]
It is possible!

I took the liberty of swiping the source code from this project and adapted it for my needs:
https://gist.github.com/ndc/7334d459c3eb0be594aad3973a488cad

**Comment by Jinhuafei** [comment]
Sorry for the late response. Looks like you have found your answer. Yes, you can plugin any IoC framework. The purpose of this repo is to demonstrate how to do that.
