### ISSUE TITLE
Struggling to get this working

### ISSUE THREAD

**Issue by Jetski5822** [aspnet/AspNetWebFormsDependencyInjection#8]
```
        void Application_Start(object sender, EventArgs e)
        {

            var container = this.AddUnity();

            container.RegisterType<IClass1, Class1>();
```

![image](https://user-images.githubusercontent.com/619530/53638426-1b869100-3c1e-11e9-858b-79d6d431c2d8.png)

![image](https://user-images.githubusercontent.com/619530/53638407-0b6eb180-3c1e-11e9-85bf-a7b086723c54.png)

Seems like something is not wired in right... any ideas?

**Comment by Jetski5822** [comment]
sorted it - my error

**Comment by heedfull** [comment]
How did you fix this?

I'm having the same issue

**Comment by gfox1984** [comment]
Typical error when targetting a version of .net lower than 4.7.2 in web.config file.
